// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "data-storage-svc/internal/model"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MediaAccessRepository is an autogenerated mock type for the MediaAccessRepository type
type MediaAccessRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: userId, mediaId
func (_m *MediaAccessRepository) Create(userId *primitive.ObjectID, mediaId *primitive.ObjectID) error {
	ret := _m.Called(userId, mediaId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID, *primitive.ObjectID) error); ok {
		r0 = rf(userId, mediaId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: userId, mediaId
func (_m *MediaAccessRepository) Get(userId *primitive.ObjectID, mediaId *primitive.ObjectID) (*model.UserMediaAccess, error) {
	ret := _m.Called(userId, mediaId)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserMediaAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID, *primitive.ObjectID) (*model.UserMediaAccess, error)); ok {
		return rf(userId, mediaId)
	}
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID, *primitive.ObjectID) *model.UserMediaAccess); ok {
		r0 = rf(userId, mediaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserMediaAccess)
		}
	}

	if rf, ok := ret.Get(1).(func(*primitive.ObjectID, *primitive.ObjectID) error); ok {
		r1 = rf(userId, mediaId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllForUser provides a mock function with given fields: userId
func (_m *MediaAccessRepository) GetAllForUser(userId *primitive.ObjectID) ([]model.UserMediaAccess, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllForUser")
	}

	var r0 []model.UserMediaAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) ([]model.UserMediaAccess, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) []model.UserMediaAccess); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserMediaAccess)
		}
	}

	if rf, ok := ret.Get(1).(func(*primitive.ObjectID) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: userId, mediaId
func (_m *MediaAccessRepository) Remove(userId *primitive.ObjectID, mediaId *primitive.ObjectID) error {
	ret := _m.Called(userId, mediaId)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID, *primitive.ObjectID) error); ok {
		r0 = rf(userId, mediaId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveAll provides a mock function with given fields: mediaId
func (_m *MediaAccessRepository) RemoveAll(mediaId *primitive.ObjectID) error {
	ret := _m.Called(mediaId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) error); ok {
		r0 = rf(mediaId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMediaAccessRepository creates a new instance of MediaAccessRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaAccessRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaAccessRepository {
	mock := &MediaAccessRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
