// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "data-storage-svc/internal/model"

	mock "github.com/stretchr/testify/mock"

	os "os"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	time "time"

	utils "data-storage-svc/internal/utils"
)

// MediaService is an autogenerated mock type for the MediaService type
type MediaService struct {
	mock.Mock
}

// Create provides a mock function with given fields: originalFilename, storageFilename, uploader, uploadedViaSharedLink
func (_m *MediaService) Create(originalFilename string, storageFilename string, uploader *primitive.ObjectID, uploadedViaSharedLink bool) (*primitive.ObjectID, utils.ServiceError) {
	ret := _m.Called(originalFilename, storageFilename, uploader, uploadedViaSharedLink)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *primitive.ObjectID
	var r1 utils.ServiceError
	if rf, ok := ret.Get(0).(func(string, string, *primitive.ObjectID, bool) (*primitive.ObjectID, utils.ServiceError)); ok {
		return rf(originalFilename, storageFilename, uploader, uploadedViaSharedLink)
	}
	if rf, ok := ret.Get(0).(func(string, string, *primitive.ObjectID, bool) *primitive.ObjectID); ok {
		r0 = rf(originalFilename, storageFilename, uploader, uploadedViaSharedLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*primitive.ObjectID)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *primitive.ObjectID, bool) utils.ServiceError); ok {
		r1 = rf(originalFilename, storageFilename, uploader, uploadedViaSharedLink)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.ServiceError)
		}
	}

	return r0, r1
}

// Delete provides a mock function with given fields: mediaId
func (_m *MediaService) Delete(mediaId *primitive.ObjectID) utils.ServiceError {
	ret := _m.Called(mediaId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 utils.ServiceError
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) utils.ServiceError); ok {
		r0 = rf(mediaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(utils.ServiceError)
		}
	}

	return r0
}

// GetAllSharedWithUser provides a mock function with given fields: userId
func (_m *MediaService) GetAllSharedWithUser(userId *primitive.ObjectID) ([]model.UserMediaAccess, utils.ServiceError) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSharedWithUser")
	}

	var r0 []model.UserMediaAccess
	var r1 utils.ServiceError
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) ([]model.UserMediaAccess, utils.ServiceError)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) []model.UserMediaAccess); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserMediaAccess)
		}
	}

	if rf, ok := ret.Get(1).(func(*primitive.ObjectID) utils.ServiceError); ok {
		r1 = rf(userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.ServiceError)
		}
	}

	return r0, r1
}

// GetAllUploadedByUser provides a mock function with given fields: userId
func (_m *MediaService) GetAllUploadedByUser(userId *primitive.ObjectID) ([]model.Media, utils.ServiceError) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUploadedByUser")
	}

	var r0 []model.Media
	var r1 utils.ServiceError
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) ([]model.Media, utils.ServiceError)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) []model.Media); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(*primitive.ObjectID) utils.ServiceError); ok {
		r1 = rf(userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.ServiceError)
		}
	}

	return r0, r1
}

// GetById provides a mock function with given fields: mediaId
func (_m *MediaService) GetById(mediaId *primitive.ObjectID) (*model.Media, utils.ServiceError) {
	ret := _m.Called(mediaId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *model.Media
	var r1 utils.ServiceError
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) (*model.Media, utils.ServiceError)); ok {
		return rf(mediaId)
	}
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) *model.Media); ok {
		r0 = rf(mediaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(*primitive.ObjectID) utils.ServiceError); ok {
		r1 = rf(mediaId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.ServiceError)
		}
	}

	return r0, r1
}

// GetData provides a mock function with given fields: mediaId, storageFileName, compressed
func (_m *MediaService) GetData(mediaId *primitive.ObjectID, storageFileName string, compressed bool) (*string, *os.File, *time.Time, utils.ServiceError) {
	ret := _m.Called(mediaId, storageFileName, compressed)

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 *string
	var r1 *os.File
	var r2 *time.Time
	var r3 utils.ServiceError
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID, string, bool) (*string, *os.File, *time.Time, utils.ServiceError)); ok {
		return rf(mediaId, storageFileName, compressed)
	}
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID, string, bool) *string); ok {
		r0 = rf(mediaId, storageFileName, compressed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(*primitive.ObjectID, string, bool) *os.File); ok {
		r1 = rf(mediaId, storageFileName, compressed)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*os.File)
		}
	}

	if rf, ok := ret.Get(2).(func(*primitive.ObjectID, string, bool) *time.Time); ok {
		r2 = rf(mediaId, storageFileName, compressed)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*time.Time)
		}
	}

	if rf, ok := ret.Get(3).(func(*primitive.ObjectID, string, bool) utils.ServiceError); ok {
		r3 = rf(mediaId, storageFileName, compressed)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(utils.ServiceError)
		}
	}

	return r0, r1, r2, r3
}

// GetMetaData provides a mock function with given fields: mediaId
func (_m *MediaService) GetMetaData(mediaId *primitive.ObjectID) (*model.MetaData, utils.ServiceError) {
	ret := _m.Called(mediaId)

	if len(ret) == 0 {
		panic("no return value specified for GetMetaData")
	}

	var r0 *model.MetaData
	var r1 utils.ServiceError
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) (*model.MetaData, utils.ServiceError)); ok {
		return rf(mediaId)
	}
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID) *model.MetaData); ok {
		r0 = rf(mediaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MetaData)
		}
	}

	if rf, ok := ret.Get(1).(func(*primitive.ObjectID) utils.ServiceError); ok {
		r1 = rf(mediaId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.ServiceError)
		}
	}

	return r0, r1
}

// IsInAlbum provides a mock function with given fields: mediaId, albumId
func (_m *MediaService) IsInAlbum(mediaId *primitive.ObjectID, albumId *primitive.ObjectID) bool {
	ret := _m.Called(mediaId, albumId)

	if len(ret) == 0 {
		panic("no return value specified for IsInAlbum")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*primitive.ObjectID, *primitive.ObjectID) bool); ok {
		r0 = rf(mediaId, albumId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMediaService creates a new instance of MediaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaService {
	mock := &MediaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
