// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	common "data-storage-svc/internal/api/common"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MyEndpoint is an autogenerated mock type for the MyEndpoint type
type MyEndpoint struct {
	mock.Mock
}

// GetCommonMiddlewares provides a mock function with no fields
func (_m *MyEndpoint) GetCommonMiddlewares() []gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCommonMiddlewares")
	}

	var r0 []gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() []gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gin.HandlerFunc)
		}
	}

	return r0
}

// GetEndpointName provides a mock function with no fields
func (_m *MyEndpoint) GetEndpointName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpointName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEndpointsList provides a mock function with no fields
func (_m *MyEndpoint) GetEndpointsList() map[common.MethodPath][]gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpointsList")
	}

	var r0 map[common.MethodPath][]gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() map[common.MethodPath][]gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[common.MethodPath][]gin.HandlerFunc)
		}
	}

	return r0
}

// GetGroupUrl provides a mock function with no fields
func (_m *MyEndpoint) GetGroupUrl() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGroupUrl")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPermissionsManager provides a mock function with no fields
func (_m *MyEndpoint) GetPermissionsManager() common.PermissionsManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsManager")
	}

	var r0 common.PermissionsManager
	if rf, ok := ret.Get(0).(func() common.PermissionsManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.PermissionsManager)
		}
	}

	return r0
}

// MyGET provides a mock function with given fields: c
func (_m *MyEndpoint) MyGET(c *gin.Context) {
	_m.Called(c)
}

// MyPOST provides a mock function with given fields: c
func (_m *MyEndpoint) MyPOST(c *gin.Context) {
	_m.Called(c)
}

// NewMyEndpoint creates a new instance of MyEndpoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMyEndpoint(t interface {
	mock.TestingT
	Cleanup(func())
}) *MyEndpoint {
	mock := &MyEndpoint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
