// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenModule is an autogenerated mock type for the TokenModule type
type TokenModule struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: Email
func (_m *TokenModule) CreateToken(Email *string) (string, error) {
	ret := _m.Called(Email)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) (string, error)); ok {
		return rf(Email)
	}
	if rf, ok := ret.Get(0).(func(*string) string); ok {
		r0 = rf(Email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(Email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenModule creates a new instance of TokenModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenModule {
	mock := &TokenModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
