name: "album-photo-api"
services:
  api:
    build: .
    command: [
      "/album", 
      "run", 
      "--api-ip=0.0.0.0", 
      "--api-port=8080", 
      "--mongo-url=mongodb://mongo:27017",
      "--data-directory=/data",
      "--api-domain=${API_DOMAIN}",
      "--debug=false"
    ]
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ${ALBUM_DATA_DIRECTORY}
        target: /data
    depends_on:
      mongo:
        condition: service_started
        restart: true
  
  mongo:
    image: ${ARCH}/mongo:4.4.1
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ${ALBUM_DATA_DIRECTORY}/mongo/
        target: /data/db



